name: Free RDP with Remote.it

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Enable RDP and Set Password
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force)
          
      - name: Install Remote.it
        run: |
          Invoke-WebRequest -Uri https://downloads.remote.it/cli/remoteit-windows.zip -OutFile remoteit.zip
          Expand-Archive remoteit.zip -DestinationPath ./remoteit

      - name: Launch Remote.it Tunnel
        run: |
          cd remoteit
          .\remoteit.exe agent install --silent
          .\remoteit.exe agent start
          .\remoteit.exe connect --rdp runneradmin P@ssw0rd!
