name: Free RDP via Remote.it

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    env:
      REMOTEIT_EMAIL: ${{ secrets.REMOTEIT_EMAIL }}
      REMOTEIT_PASSWORD: ${{ secrets.REMOTEIT_PASSWORD }}

    steps:
      - name: Enable RDP & Set Password
        shell: powershell
        run: |
          Set-ItemProperty HKLM:\System\CurrentControlSet\Control\Terminal Server -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-LocalUser -Name 'runneradmin' -Password (ConvertTo-SecureString "P@ssw0rd!" -AsPlainText -Force)

      - name: Install remote.it
        shell: powershell
        run: winget install --id=remoteit.remoteit -e --silent

      - name: Configure remote.it
        shell: powershell
        run: |
          remoteit register --email $Env:REMOTEIT_EMAIL --password $Env:REMOTEIT_PASSWORD
          remoteit service add --name RDP --protocol tcp --port 3389
          remoteit connect --name RDP
